name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build left half (central)
        uses: zmkfirmware/zmk@main
        with:
          board: nice_nano_v2
          shield: split36_left
          artifact-name: zmk-left

      - name: Build right half (peripheral)
        uses: zmkfirmware/zmk@main
        with:
          board: nice_nano_v2
          shield: split36_right
          artifact-name: zmk-right
