name: Build ZMK firmware

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up west and dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build python3-pip
          pip install west
          west init -l app
          west update
          west zephyr-export
          pip install -r app/zephyr/scripts/requirements.txt

      - name: Build firmware for left side
        run: west build -p -b nice_nano_v2 -- -DSHIELD=split36_left -DZMK_CONFIG=${{ github.workspace }}

      - name: Build firmware for right side
        run: west build -p -b nice_nano_v2 -- -DSHIELD=split36_right -DZMK_CONFIG=${{ github.workspace }}

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
